version: "2"
services:

    redis:
      image: redis:alpine
      ports:
        - "6379"
      environment:
        - SECRET_KEY=aabbcc
        - ENV_IS_SET

    frontend:
      image: busybox
      #entrypoint: []
      command: ["/bin/busybox", "httpd", "-f", "-p", "8080"]
      working_dir: /
      environment:
        SECRET_KEY2: aabbcc
        ENV_IS_SET2:
      ports:
        - "8080"
      links:
        - redis:myredis
      labels:
        my.label: my_value

#tmpfs: /run
#tmpfs:
#  - /run
#  - /tmp
#user: postgresql
#working_dir: /code
#domainname: foo.com
#hostname: foo
#ipc: host
#mac_address: 02:42:ac:11:65:43
#privileged: true
#read_only: true
#shm_size: 64M
#stdin_open: true
#tty: true
