web:
  image: tuna/docker-counter23
  ports:
    - "5000:5000"
  links:
    - redis
  labels:
    kompose.service.expose: "batman.example.com"
    kompose.service.expose.tls-secret: "test-secret"
redis:
  image: redis:3.0
  ports:
    - "6379"
