version: "3"

services:
  foo:
    labels:
      kompose.service.type: headless
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 50M
        reservations:
          cpus: '0.001'
          memory: 20M
    image: redis
